export const themeSelection = {
  currentTheme: 'blackYellow',
  themes: {
    blackYellow: {
      bg: '#1D1D1D',
      // Navbar
      navTitle: '#FEEA36',
      navItem: '#DCDCDC',
      navItemHover: '#FEEA36',
      // Drawer
      bgDrawer: '#DCDCDC',
      menuDrawer: '#FEEA36',
      closeDrawer: '#1D1D1D',
      titleDrawer: '#1D1D1D',
      itemsDrawer: '#1D1D1D',
      ctContainerDrawer: '#FEEA36',
      ctTextDrawer: '#1D1D1D',
      logoutContainerDrawer: '#1D1D1D',
      logoutTextDrawer: '#FEEA36',
      // Options
      optionColor: '#FEEA36',
      // Dashboard
      welcomeTitle: '#DCDCDC',
      youHaveAddedContainer: '#FEEA36',
      youHaveAddedText: '#1D1D1D',
      borderColorChoice: '#FEEA36',
      iconChoiceColor: '#FEEA36',
      textChoice: '#DCDCDC',
      // Add Song
      addSongTitle: '#DCDCDC',
      songTitleLabel: '#DCDCDC',
      inputSelected: '#FEEA36',
      inputBottomLine: '#dcdcdc6b',
      bgAddSongBtn: '#FEEA36',
      textAddSong: '#1D1D1D',
      addSongBtnHover: '#feea36d8',
      borderTextArea: '#dcdcdc6b',
      // Songs List
      songsListTitle: '#DCDCDC',
      songName: '#DCDCDC',
      songAction: '#FEEA36',
      songBox: '#FEEA36',
      songTopLine: '#FEEA36',
      songsSelectedBtn: '#FEEA36',
      songsSelectedBtnHover: '#feea36d8',
      iconSongsSelected: '#1D1D1D',
      numberSongsSelected: '#1D1D1D',
      // Custom Lists
      listContainer: '#FEEA36',
      customTitle: '#1D1D1D',
      dividerColor: '#1D1D1D',
      btnColor: '#1D1D1D',
      bgBtnPlayList: '#1D1D1D',
      colorTextBtn: '#FEEA36',
      bgBtnPlayListHover: '#1D1D1Dd8',
      division: '#FEEA36',
      // Temporal Title Textfield
      textFieldColor: '#1D1D1D',
      textFieldOne: '#1D1D1D',
      textFieldTwo: '#1D1D1Dde',
      // Custom Lists - Modal
      modalBox: '#FEEA36',
      closeModal: '#1D1D1D',
      modalText: '#1D1D1D',
      modalBoxBorder: '#1D1D1D',
      modalBoxIcon: '#1D1D1D',
      // Random Songs with BPM
      songInfoBox: '#FEEA36',
      bpmTextColor: '#DCDCDC',
      bpmBar: '#FEEA36',
      bpmBarHover: '#feea3629',
      grInfoText: '#1D1D1D',
      // Random Videos
      videoExample: '#FEEA36',
      iconExample: '#FEEA36',
      // Loading
      colorBarOne: '#FEEA36',
      colorBarTwo: '#FEEA36',
      barColorBg: '#feea3538',
      // Next Theme
      nextTheme: 'blackYellow',
      boxOne: '#FEEA36',
      boxTwo: '#1D1D1D',
    },
    yellowBlack: {
      bg: '#FEEA36',
      // Navbar
      navTitle: '#1D1D1D',
      navItem: '#1D1D1D',
      navItemHover: '#1D1D1D',
      // Drawer
      bgDrawer: '#DCDCDC',
      menuDrawer: '#1D1D1D',
      closeDrawer: '#1D1D1D',
      titleDrawer: '#1D1D1D',
      itemsDrawer: '#1D1D1D',
      ctContainerDrawer: '#FEEA36',
      ctTextDrawer: '#1D1D1D',
      logoutContainerDrawer: '#1D1D1D',
      logoutTextDrawer: '#FEEA36',
      // Options
      optionColor: '#1D1D1D',
      // Dashboard
      welcomeTitle: '#1D1D1D',
      youHaveAddedContainer: '#1D1D1D',
      youHaveAddedText: '#FEEA36',
      borderColorChoice: '#1D1D1D',
      iconChoiceColor: '#1D1D1D',
      textChoice: '#1D1D1D',
      // Add Song
      addSongTitle: '#1D1D1D',
      songTitleLabel: '#1D1D1D',
      inputSelected: '#1D1D1D',
      inputBottomLine: '#1D1D1D6b',
      bgAddSongBtn: '#1D1D1D',
      textAddSong: '#FEEA36',
      addSongBtnHover: '#1D1D1Dd8',
      borderTextArea: '#dcdcdc6b',
      // Songs List
      songsListTitle: '#1D1D1D',
      songName: '#1D1D1D',
      songAction: '#1D1D1D',
      songBox: '#1D1D1D',
      songTopLine: '#1D1D1D',
      songsSelectedBtn: '#1D1D1D',
      songsSelectedBtnHover: '#1D1D1Dd8',
      iconSongsSelected: '#FEEA36',
      numberSongsSelected: '#FEEA36',
      // Custom Lists
      listContainer: '#1D1D1D',
      customTitle: '#FEEA36',
      dividerColor: '#FEEA36',
      btnColor: '#FEEA36',
      bgBtnPlayList: '#FEEA36',
      colorTextBtn: '#1D1D1D',
      bgBtnPlayListHover: '#FEEA36d8',
      division: '#1D1D1D',
      // Temporal Title Textfield
      textFieldColor: '#FEEA36',
      textFieldOne: '#FEEA36',
      textFieldTwo: '#FEEA36de',
      // Custom Lists - Modal
      modalBox: '#FEEA36',
      closeModal: '#1D1D1D',
      modalText: '#1D1D1D',
      modalBoxBorder: '#1D1D1D',
      modalBoxIcon: '#1D1D1D',
      // Random Songs with BPM
      songInfoBox: '#1D1D1D',
      bpmTextColor: '#1D1D1D',
      bpmBar: '#1D1D1D',
      bpmBarHover: '#1D1D1D29',
      grInfoText: '#FEEA36',
      // Random Videos
      videoExample: '#1D1D1D',
      iconExample: '#1D1D1D',
      // Loading
      colorBarOne: '#1D1D1D',
      colorBarTwo: '#1D1D1D',
      barColorBg: '#1D1D1D38',
      // Next Theme
      nextTheme: 'Blue/White',
      boxOne: '#11384A',
      boxTwo: '#DCDCDC',
    },
    blueWhite: {
      bg: '#09212c',
      bgClear: '#11384A',
      bgDark: '#0D191C',
      // Navbar
      navTitle: '#61DAFB',
      navItem: '#DCDCDC',
      navItemHover: '#61DAFB',
      // Drawer
      bgDrawer: '#61DAFB',
      menuDrawer: '#61DAFB',
      closeDrawer: '#10374A',
      titleDrawer: '#10374A',
      itemsDrawer: '#1D1D1D',
      ctContainerDrawer: '#DCDCDC',
      ctTextDrawer: '#1D1D1D',
      logoutContainerDrawer: '#10374A',
      logoutTextDrawer: '#DCDCDC',
      // Options
      optionColor: '#61DAFB',
      // Dashboard
      welcomeTitle: '#DCDCDC',
      youHaveAddedContainer: '#DCDCDC',
      youHaveAddedText: '#10374A',
      borderColorChoice: '#DCDCDC',
      iconChoiceColor: '#61DAFB',
      textChoice: '#DCDCDC',
      // Add Song
      addSongTitle: '#DCDCDC',
      songTitleLabel: '#DCDCDC',
      inputSelected: '#61DAFB',
      inputBottomLine: '#DCDCDC6b',
      bgAddSongBtn: '#61DAFB',
      textAddSong: '#10374A',
      addSongBtnHover: '#61DAFBd8',
      borderTextArea: '#dcdcdc6b',
      // Songs List
      songsListTitle: '#DCDCDC',
      songName: '#DCDCDC',
      songAction: '#61DAFB',
      songBox: '#61DAFB',
      songTopLine: '#61DAFB',
      songsSelectedBtn: '#61DAFB',
      songsSelectedBtnHover: '#61DAFBd8',
      iconSongsSelected: '#10374A',
      numberSongsSelected: '#10374A',
      // Custom Lists
      listContainer: '#61DAFB',
      customTitle: '#10374A',
      dividerColor: '#10374A',
      btnColor: '#10374A',
      bgBtnPlayList: '#10374A',
      colorTextBtn: '#DCDCDC',
      bgBtnPlayListHover: '#61DAFBd8',
      division: '#61DAFB',
      // Temporal Title Textfield
      textFieldColor: '#10374A',
      textFieldOne: '#10374A',
      textFieldTwo: '#10374Ade',
      // Custom Lists - Modal
      modalBox: '#DCDCDC',
      closeModal: '#10374A',
      modalText: '#10374A',
      modalBoxBorder: '#10374A',
      modalBoxIcon: '#10374A',
      // Random Songs with BPM
      songInfoBox: '#61DAFB',
      bpmTextColor: '#DCDCDC',
      bpmBar: '#61DAFB',
      bpmBarHover: '#61DAFB29',
      grInfoText: '#10374A',
      // Random Videos
      videoExample: '#61DAFB',
      iconExample: '#61DAFB',
      // Loading
      colorBarOne: '#61DAFB',
      colorBarTwo: '#61DAFB',
      barColorBg: '#61DAFB38',
      // Next Theme
      nextTheme: 'White/Blue',
      boxOne: '#DCDCDC',
      boxTwo: '#10374A',
    },
    whiteBlue: {
      bg: '#DCDCDC',
      // Navbar
      navTitle: '#10374A',
      navItem: '#10374A',
      navItemHover: '#10374A',
      // Drawer
      bgDrawer: '#1D1D1D',
      menuDrawer: '#10374A',
      closeDrawer: '#DCDCDC',
      titleDrawer: '#61DAFB',
      itemsDrawer: '#61DAFB',
      ctContainerDrawer: '#DCDCDC',
      ctTextDrawer: '#1D1D1D',
      logoutContainerDrawer: '#10374A',
      logoutTextDrawer: '#DCDCDC',
      // Options
      optionColor: '#10374A',
      // Dashboard
      welcomeTitle: '#10374A',
      youHaveAddedContainer: '#10374A',
      youHaveAddedText: '#DCDCDC',
      borderColorChoice: '#10374A',
      iconChoiceColor: '#10374A',
      textChoice: '#10374A',
      // Add Song
      addSongTitle: '#10374A',
      songTitleLabel: '#10374A',
      inputSelected: '#10374A',
      inputBottomLine: '#10374A6b',
      bgAddSongBtn: '#10374A',
      textAddSong: '#DCDCDC',
      addSongBtnHover: '#10374Ad8',
      borderTextArea: '#dcdcdc6b',
      // Songs List
      songsListTitle: '#10374A',
      songName: '#10374A',
      songAction: '#10374A',
      songBox: '#10374A',
      songTopLine: '#10374A',
      songsSelectedBtn: '#10374A',
      songsSelectedBtnHover: '#10374Ad8',
      iconSongsSelected: '#DCDCDC',
      numberSongsSelected: '#DCDCDC',
      // Custom Lists
      listContainer: '#10374A',
      customTitle: '#DCDCDC',
      dividerColor: '#DCDCDC',
      btnColor: '#DCDCDC',
      bgBtnPlayList: '#DCDCDC',
      colorTextBtn: '#10374A',
      bgBtnPlayListHover: '#DCDCDCd8',
      division: '#10374A',
      // Temporal Title Textfield
      textFieldColor: '#DCDCDC',
      textFieldOne: '#DCDCDC',
      textFieldTwo: '#DCDCDCde',
      // Custom Lists - Modal
      modalBox: '#DCDCDC',
      closeModal: '#10374A',
      modalText: '#10374A',
      modalBoxBorder: '#10374A',
      modalBoxIcon: '#10374A',
      // Random Songs with BPM
      songInfoBox: '#10374A',
      bpmTextColor: '#10374A',
      bpmBar: '#10374A',
      bpmBarHover: '#10374A29',
      grInfoText: '#DCDCDC',
      // Random Videos
      videoExample: '#10374A',
      iconExample: '#10374A',
      // Loading
      colorBarOne: '#10374A',
      colorBarTwo: '#10374A',
      barColorBg: '#10374A38',
      // Next Theme
      nextTheme: 'Dark Red',
      boxOne: '#4F0303',
      boxTwo: '#FF3434',
    },
    redDark: {
      bg: '#09212c',
      bgClear: '#4F0303',
      bgDark: '#1C0C0C',
      // Navbar
      navTitle: '#FF3434',
      navItem: '#DCDCDC',
      navItemHover: '#FF3434',
      // Drawer
      bgDrawer: '#DCDCDC',
      menuDrawer: '#FF3434',
      closeDrawer: '#4F0303',
      titleDrawer: '#4F0303',
      itemsDrawer: '#4F0303',
      ctContainerDrawer: '#FF3131',
      ctTextDrawer: '#4F0303',
      logoutContainerDrawer: '#4F0303',
      logoutTextDrawer: '#DCDCDC',
      // Options
      optionColor: '#FF3434',
      // Dashboard
      welcomeTitle: '#DCDCDC',
      youHaveAddedContainer: '#FF3434',
      youHaveAddedText: '#4F0303',
      borderColorChoice: '#FF3434',
      iconChoiceColor: '#FF3434',
      textChoice: '#DCDCDC',
      // Add Song
      addSongTitle: '#DCDCDC',
      songTitleLabel: '#DCDCDC',
      inputSelected: '#FF3434',
      inputBottomLine: '#FF34346b',
      bgAddSongBtn: '#FF3434',
      textAddSong: '#4F0303',
      addSongBtnHover: '#FF3434d8',
      borderTextArea: '#dcdcdc6b',
      // Songs List
      songsListTitle: '#DCDCDC',
      songName: '#DCDCDC',
      songAction: '#FF3434',
      songBox: '#FF3434',
      songTopLine: '#FF3434',
      songsSelectedBtn: '#FF3434',
      songsSelectedBtnHover: '#FF3434d8',
      iconSongsSelected: '#4F0303',
      numberSongsSelected: '#4F0303',
      // Custom Lists
      listContainer: '#FF3434',
      customTitle: '#4F0303',
      dividerColor: '#4F0303',
      btnColor: '#4F0303',
      bgBtnPlayList: '#4F0303',
      colorTextBtn: '#DCDCDC',
      bgBtnPlayListHover: '#4F0303d8',
      division: '#FF3434',
      // Temporal Title Textfield
      textFieldColor: '#4F0303',
      textFieldOne: '#4F0303',
      textFieldTwo: '#4F0303de',
      // Custom Lists - Modal
      modalBox: '#FF3434',
      closeModal: '#4F0303',
      modalText: '#4F0303',
      modalBoxBorder: '#4F0303',
      modalBoxIcon: '#4F0303',
      // Random Songs with BPM
      songInfoBox: '#FF3434',
      bpmTextColor: '#DCDCDC',
      bpmBar: '#FF3434',
      bpmBarHover: '#FF343429',
      grInfoText: '#4F0303',
      // Random Videos
      videoExample: '#FF3434',
      iconExample: '#FF3434',
      // Loading
      colorBarOne: '#FF3434',
      colorBarTwo: '#FF3434',
      barColorBg: '#FF343438',
      // Next Theme
      nextTheme: 'Red',
      boxOne: '#FF3131',
      boxTwo: '#4F0303',
    },
    red: {
      bg: '#FF3131',
      // Navbar
      navTitle: '#4F0303',
      navItem: '#4F0303',
      navItemHover: '#4F0303',
      // Drawer
      bgDrawer: '#DCDCDC',
      menuDrawer: '#4F0303',
      closeDrawer: '#4F0303',
      titleDrawer: '#4F0303',
      itemsDrawer: '#4F0303',
      ctContainerDrawer: '#FF3131',
      ctTextDrawer: '#4F0303',
      logoutContainerDrawer: '#4F0303',
      logoutTextDrawer: '#DCDCDC',
      // Options
      optionColor: '#4F0303',
      // Dashboard
      welcomeTitle: '#4F0303',
      youHaveAddedContainer: '#4F0303',
      youHaveAddedText: '#DCDCDC',
      borderColorChoice: '#4F0303',
      iconChoiceColor: '#4F0303',
      textChoice: '#4F0303',
      // Add Song
      addSongTitle: '#4F0303',
      songTitleLabel: '#4F0303',
      inputSelected: '#4F0303',
      inputBottomLine: '#4F03036b',
      bgAddSongBtn: '#4F0303',
      textAddSong: '#DCDCDC',
      addSongBtnHover: '#4F0303d8',
      borderTextArea: '#dcdcdc6b',
      // Songs List
      songsListTitle: '#4F0303',
      songName: '#4F0303',
      songAction: '#4F0303',
      songBox: '#4F0303',
      songTopLine: '#4F0303',
      songsSelectedBtn: '#4F0303',
      songsSelectedBtnHover: '#4F0303d8',
      iconSongsSelected: '#DCDCDC',
      numberSongsSelected: '#DCDCDC',
      // Custom Lists
      listContainer: '#4F0303',
      customTitle: '#FF3434',
      dividerColor: '#FF3434',
      btnColor: '#FF3434',
      bgBtnPlayList: '#FF3434',
      colorTextBtn: '#4F0303',
      bgBtnPlayListHover: '#FF3434d8',
      division: '#4F0303',
      // Temporal Title Textfield
      textFieldColor: '#FF3434',
      textFieldOne: '#FF3434',
      textFieldTwo: '#FF3434de',
      // Custom Lists - Modal
      modalBox: '#FF3434',
      closeModal: '#4F0303',
      modalText: '#4F0303',
      modalBoxBorder: '#4F0303',
      modalBoxIcon: '#4F0303',
      // Random Songs with BPM
      songInfoBox: '#4F0303',
      bpmTextColor: '#4F0303',
      bpmBar: '#4F0303',
      bpmBarHover: '#4F030329',
      grInfoText: '#FF3434',
      // Random Videos
      videoExample: '#4F0303',
      iconExample: '#4F0303',
      // Loading
      colorBarOne: '#4F0303',
      colorBarTwo: '#4F0303',
      barColorBg: '#4F030338',
      // Next Theme
      nextTheme: 'Black/Yellow',
      boxOne: '#1D1D1D',
      boxTwo: '#FEEA36',
    },
  },
};
